// Code generated by "stringer -type=TokenType -trimprefix=Token"; DO NOT EDIT.

package sqlparse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenUnknown-0]
	_ = x[TokenWhitespace-1]
	_ = x[TokenNewline-2]
	_ = x[TokenKeyword-3]
	_ = x[TokenKeywordCTE-4]
	_ = x[TokenOperator-5]
	_ = x[TokenUseAsKeyword-6]
	_ = x[TokenPunctuation-7]
	_ = x[TokenName-8]
	_ = x[TokenWildcard-9]
	_ = x[TokenNumberInteger-10]
	_ = x[TokenNumberFloat-11]
	_ = x[TokenString-12]
}

const _TokenType_name = "UnknownWhitespaceNewlineKeywordKeywordCTEOperatorUseAsKeywordPunctuationNameWildcardNumberIntegerNumberFloatString"

var _TokenType_index = [...]uint8{0, 7, 17, 24, 31, 41, 49, 61, 72, 76, 84, 97, 108, 114}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
